spring.application.name=limitenhancement-service
server.port=8087
spring.cache.jcache.config=classpath:ehcache.xml
#springdoc.swagger-ui.operationsSorter=method
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework=ERROR
#logging.level.root=ERROR
logging.level.com.axisbank=DEBUG


spring.main.allow-bean-definition-overriding=true

encryption.secret.key={IB:'12345678',MB:'87654321',SM:'98734568',AA:'123456789'}
encryption.salt.key={IB:'123',MB:'321',SM:'587',AA:'456'}
#Encryption IV key must be 16 character long
encryption.iv.key=8765432112345678

management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true

microservice.accounts.URL=https://accounts-axisms-uat.apps.msocribuat.axisb.com/api/v1/account/aggregator/
app.rate.limit=5
app.rate.durationinms=60000
#<cust_id>?schemeTypes=SBA,CAA
